apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "laravel-cicd.fullname" . }}
  labels:
    {{- include "laravel-cicd.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "laravel-cicd.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "laravel-cicd.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "laravel-cicd.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: laravel-cicd-nginx
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "leloimr/laravel-cicd-nginx:{{ .Values.tag | default .Chart.AppVersion }}"
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          
        - name: laravel-cicd-app
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "leloimr/laravel-cicd-app:{{ .Values.tag | default .Chart.AppVersion }}"
          imagePullPolicy: Always
          ports:
            - containerPort: 9000
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        #   volumeMounts:
        #     - name: data
        #       mountPath: /var/www/html/
    #   volumes:
    #     - name: data
    #       emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
